[package]
name = "relay-control"
version = "0.1.21"
edition = "2024"

[dependencies]
tokio = { workspace = true }
tokio-util = { version = "0.7", features = ["io"] }
base64 = "0.22"
ed25519-dalek = "2.2.0"
rand = "0.8"
uuid = { version = "1.0", features = ["v4"] }
